# Throwing and Throwing Mechanics

## Basics of Throwing Mechanics

<div style="text-align:center;">
<iframe width="560" height="315"
        src="https://www.youtube.com/embed/oWubA0m1cNA?start=0&end=102&autoplay=0&mute=1&loop=1&playlist=oWubA0m1cNA"
        frameborder="0"
        allow="autoplay; encrypted-media"
        allowfullscreen>
</iframe>
</div>

<div style="text-align:center;">
<iframe width="560" height="315"
        src="https://www.youtube.com/embed/jTwjtiYj9Uo?autoplay=0&mute=1&loop=1&playlist=jTwjtiYj9Uo"
        frameborder="0"
        allow="autoplay; encrypted-media"
        allowfullscreen>
</iframe>
</div>


<div style="text-align:center;">
<iframe width="315" height="560"
        src="https://www.youtube.com/embed/BsPrlBU5mUY?autoplay=1&mute=1&loop=1&playlist=BsPrlBU5mUY"
        frameborder="0"
        allow="autoplay; encrypted-media"
        allowfullscreen>
</iframe>
</div>

### Work the Stretch


<div style="text-align:center;">
<iframe width="560" height="315"
        src="https://www.youtube.com/embed/oWubA0m1cNA?start=102&end=112&autoplay=0&mute=0&loop=0&playlist=oWubA0m1cNA"
        frameborder="0"
        allow="autoplay; encrypted-media"
        allowfullscreen>
</iframe>
</div>



### Work the Shuffle


<div style="text-align:center;">
<iframe width="560" height="315"
        src="https://www.youtube.com/embed/oWubA0m1cNA?start=113&end=133&autoplay=0&mute=0&loop=0&playlist=oWubA0m1cNA"
        frameborder="0"
        allow="autoplay; encrypted-media"
        allowfullscreen>
</iframe>
</div>


### Get to Tight V Position

<div style="text-align:center;">
  <blockquote class="instagram-media"
    data-instgrm-captioned
    data-instgrm-permalink="https://www.instagram.com/tv/CH8YrTRgMZS/?utm_source=ig_embed&amp;utm_campaign=loading"
    data-instgrm-version="14"
    style="background:#FFF; border:0; border-radius:3px;
           box-shadow:0 0 1px 0 rgba(0,0,0,0.5),
                       0 1px 10px 0 rgba(0,0,0,0.15);
           margin:1px; max-width:540px; min-width:326px; padding:0;
           width:99.375%; width:-webkit-calc(100% - 2px);
           width:calc(100% - 2px);">
  </blockquote>
  <script async src="//www.instagram.com/embed.js"></script>
</div>


## Throwing Warmup Routine

### Standard Trent Mongero Routine

-  Wrist Flips – seated, kneeling, or standing (Focus: On top and behind ball. Good rotation)  
-  Kneeling Figure 8 (Focus: Upper body rhythm and separation)  
-  Kneeling Power Position (Focus: Get a feel for a good power position with alignment)  
-  Standing Figure 8 (Focus: Tie in lower body to rhythm and separation)  
-  Standing Power Position (Focus: Tie in lower body alignment and action into power position)  
-  Tempo Arm Swings (Focus: Rhythm and Tempo of entire body as it loads to throw)  
-  Boxers (Focus: Syncs the lower body and upper body to throw using quick feet)  
-  Jump-Backs (Focus: Exaggerate the loading of the body against the backside)  
-  180’s/360’s (Focus: Learn to throw the ball confidently to a blind target moving feet in extreme ways)  
-  Throw on run (Focus: Throw off correct foot and incorrect foot using various arm slots)  
-  Specialty throwing by position – (Focus: Execute throws that are specific to players’ defensive position)  
-  Long Toss Distance Progression to Distance of Player Choice. (Focus: Improve and maintain arm strength)  
-  On top at 90 ft. 5- 10 throws (Focus: Gain confidence to throw ball hard and accurately. Getting on top)  
-  Quick Feet/Quick Release Competition at 30 or 45 feet (Focus: How many transitions in 20 seconds)  

Additional throwing that can be occasionally added to routine:

-  Pick-off moves with partner  
-  Rundowns – Divide team into 3 groups and use cones at 90 feet. Execute your rundown rules  
-  Glove flips only (no hands). How many from 10 feet in 20 seconds. Compete  
-  Double play feed drill – how many flips, etc. to one another in 20 seconds  


<iframe width="560" height="315" 
src="https://www.youtube.com/embed/t-PIkA-gDtk?start=602" 
title="Trent Mongero – The Most Important 20 Min of Practice" 
frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" 
allowfullscreen>
</iframe>


##  Plyo Drills

###  Daily Routine

*  Warmup  
*  Pivot Pics   
   -  Player stands 90 degrees to wall throw arm closest to the wall.  With feet planted, turn to face the wall and throw the ball against the wall.
*  Hip Sequencing    
   -  Player stands 90 degrees to wall with glove arm closest to wall.  Come to power.  Throw the ball against the wall.   
*  Split-stance Lasso  
   -  Player stands 90 degrees to wall with glove arm closest to wall.  Come to power and make a circle with your throwing hand.  Throw the ball against the wall.   
*  Roll-ins  
   -  Player begins square to the wall.  Takes 2 - 3 steps towards the wall and throws.  Make sure to follow through.   
*  Drive off Back Legs  
   -  Player starts 90 degrees to wall with glove side facing the wall.  Player jumps back and pushes off their back leg while throwing the ball.   
   
<div style="max-width:540px; margin:1em auto;">
  <blockquote class="instagram-media"
    data-instgrm-permalink="https://www.instagram.com/reel/DQx5knEjA9x/?utm_source=ig_embed&utm_campaign=loading"
    data-instgrm-version="14"
    style="background:#FFF; border:0; border-radius:3px;
           box-shadow:0 0 1px rgba(0,0,0,0.5),
                       0 1px 10px rgba(0,0,0,0.15);
           padding:0; width:100%;">
  </blockquote>
</div>

<script async src="https://www.instagram.com/embed.js"></script>




