# Fielding Drills




## Forehand



### Getting Around the Ball

<div style="text-align:center;">
<iframe width="315" height="560"
        src="https://www.youtube.com/embed/nXXQcbLBDrM?autoplay=1&mute=1&loop=0&playlist=nXXQcbLBDrM"
        frameborder="0"
        allow="autoplay; encrypted-media"
        allowfullscreen>
</iframe>
</div>



### Crossover Dailies

<div style="text-align:center;">
  <blockquote class="instagram-media"
    data-instgrm-captioned
    data-instgrm-permalink="https://www.instagram.com/reel/C3oHZljOlqu/?utm_source=ig_embed&amp;utm_campaign=loading"
    data-instgrm-version="14"
    style="background:#FFF; border:0; border-radius:3px;
           box-shadow:0 0 1px 0 rgba(0,0,0,0.5),
                       0 1px 10px 0 rgba(0,0,0,0.15);
           margin:1px; max-width:540px; min-width:326px; padding:0;
           width:99.375%; width:-webkit-calc(100% - 2px);
           width:calc(100% - 2px);">
  </blockquote>
  <script async src="//www.instagram.com/embed.js"></script>
</div>




### Pancake Hoop Drill

<div style="max-width:540px; margin:1em auto;">
  <blockquote class="instagram-media"
    data-instgrm-permalink="https://www.instagram.com/reel/DCrzt0jx6XQ/?utm_source=ig_embed&utm_campaign=loading"
    data-instgrm-version="14"
    style="background:#FFF; border:0; border-radius:3px;
           box-shadow:0 0 1px rgba(0,0,0,0.5),
                       0 1px 10px rgba(0,0,0,0.15);
           padding:0; width:100%;">
  </blockquote>
</div>

<script async src="https://www.instagram.com/embed.js"></script>


### Flat Glove Work

<iframe width="315" height="560"
  src="https://www.youtube.com/embed/-5PNbrT2sB8"
  title="YouTube Short"
  frameborder="0"
  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
  allowfullscreen>
</iframe>




### Footwork Shuffle

<div style="text-align:center;">
<iframe width="560" height="315"
        src="https://www.youtube.com/embed/aXXhaomzYZA?start=0&end=57&autoplay=0&mute=1&loop=0&playlist=aXXhaomzYZA"
        frameborder="0"
        allow="autoplay; encrypted-media"
        allowfullscreen>
</iframe>
</div>





### Advanced Knee Ground Balls (Fungo)

<div style="text-align:center;">
<iframe width="560" height="315"
        src="https://www.youtube.com/embed/nwT3mBgwQQQ?start=50&end=77&autoplay=0&mute=1&loop=0&playlist=nwT3mBgwQQQ"
        frameborder="0"
        allow="autoplay; encrypted-media"
        allowfullscreen>
</iframe>
</div>


### Short Forehand Fungos

<div style="text-align:center;">
<iframe width="560" height="315"
        src="https://www.youtube.com/embed/aXXhaomzYZA?start=111&end=130&autoplay=0&mute=1&loop=0&playlist=aXXhaomzYZA"
        frameborder="0"
        allow="autoplay; encrypted-media"
        allowfullscreen>
</iframe>
</div>




### Active Feet Middle Infield

<div style="text-align:center;">
  <blockquote class="instagram-media"
    data-instgrm-captioned
    data-instgrm-permalink="https://www.instagram.com/p/BfHsf7QhP6m/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA=="
    data-instgrm-version="14"
    style="background:#FFF; border:0; border-radius:3px;
           box-shadow:0 0 1px 0 rgba(0,0,0,0.5),
                       0 1px 10px 0 rgba(0,0,0,0.15);
           margin:1px; max-width:540px; min-width:326px; padding:0;
           width:99.375%; width:-webkit-calc(100% - 2px);
           width:calc(100% - 2px);">
  </blockquote>
  <script async src="//www.instagram.com/embed.js"></script>
</div>





## Backhand



### Fix Your Backhand in 30 Seconds


<div style="max-width:540px; margin:1em auto;">
  <blockquote class="instagram-media"
    data-instgrm-permalink="https://www.instagram.com/reel/DQUZcmWjQKj/?utm_source=ig_embed&utm_campaign=loading"
    data-instgrm-version="14"
    style="background:#FFF; border:0; border-radius:3px;
           box-shadow:0 0 1px rgba(0,0,0,0.5),0 1px 10px rgba(0,0,0,0.15);
           padding:0; width:100%;">
  </blockquote>
  <script async src="https://www.instagram.com/embed.js"></script>
</div>



### Backhand Daily From a Cone

<div style="text-align:center;">
<iframe width="560" height="315"
        src="https://www.youtube.com/embed/aXXhaomzYZA?start=206&end=205&autoplay=0&mute=1&loop=0&playlist=aXXhaomzYZA"
        frameborder="0"
        allow="autoplay; encrypted-media"
        allowfullscreen>
</iframe>
</div>



### Backhand Ladder

<div style="text-align:center;">
<iframe width="560" height="315"
        src="https://www.youtube.com/embed/aXXhaomzYZA?start=491&end=505&autoplay=0&mute=1&loop=0&playlist=aXXhaomzYZA"
        frameborder="0"
        allow="autoplay; encrypted-media"
        allowfullscreen>
</iframe>
</div>


### Rolled Backhand Daily

<div style="text-align:center;">
<iframe width="560" height="315"
        src="https://www.youtube.com/embed/aXXhaomzYZA?start=81&end=90&autoplay=0&mute=1&loop=1&playlist=aXXhaomzYZA"
        frameborder="0"
        allow="autoplay; encrypted-media"
        allowfullscreen>
</iframe>
</div>



###  Backhand Angles

<div style="text-align:center;">
  <blockquote 
    class="instagram-media"
    data-instgrm-captioned
    data-instgrm-permalink="https://www.instagram.com/reel/DQrcYo9ERpx/?utm_source=ig_embed&utm_campaign=loading"
    data-instgrm-version="14"
    style="background:#FFF; border:0; border-radius:3px;
           box-shadow:0 0 1px 0 rgba(0,0,0,0.5),
                       0 1px 10px 0 rgba(0,0,0,0.15);
           margin:1px; max-width:540px; min-width:326px; padding:0;
           width:99.375%; width:-webkit-calc(100% - 2px);
           width:calc(100% - 2px);">
  </blockquote>

  <script async src="//www.instagram.com/embed.js"></script>
</div>



## Reaction/ Speed 



### First Step Quickness

<div style="text-align:center;">
<iframe width="315" height="560"
        src="https://www.youtube.com/embed/bOo8tnLWRlo?autoplay=1&mute=1&loop=1&playlist=bOo8tnLWRlo"
        frameborder="0"
        allow="autoplay; encrypted-media"
        allowfullscreen>
</iframe>
</div>


### Diving Play Up The Middle

<div style="text-align:center;">
  <blockquote class="instagram-media"
    data-instgrm-captioned
    data-instgrm-permalink="https://www.instagram.com/p/CKP1IxMA111/?utm_source=ig_embed&amp;utm_campaign=loading"
    data-instgrm-version="14"
    style="background:#FFF; border:0; border-radius:3px;
           box-shadow:0 0 1px 0 rgba(0,0,0,0.5),
                       0 1px 10px 0 rgba(0,0,0,0.15);
           margin:1px; max-width:540px; min-width:326px; padding:0;
           width:99.375%; width:-webkit-calc(100% - 2px);
           width:calc(100% - 2px);">
  </blockquote>
  <script async src="//www.instagram.com/embed.js"></script>
</div>




## Double Play / Pivot Work



### Double Plays with Ladder

<div style="text-align:center;">
<iframe width="560" height="315"
        src="https://www.youtube.com/embed/aXXhaomzYZA?start=58&end=80&autoplay=0&mute=1&loop=0&playlist=aXXhaomzYZA"
        frameborder="0"
        allow="autoplay; encrypted-media"
        allowfullscreen>
</iframe>
</div>

### Double Play Side-Arm Feeds


<div style="text-align:center;">
  <blockquote 
    class="instagram-media" 
    data-instgrm-captioned
    data-instgrm-permalink="https://www.instagram.com/p/CGVTr8oAat4/?utm_source=ig_embed&amp;utm_campaign=loading" 
    data-instgrm-version="14"
    style="background:#FFF; border:0; border-radius:3px; 
           box-shadow:0 0 1px 0 rgba(0,0,0,0.5),
                       0 1px 10px 0 rgba(0,0,0,0.15);
           margin:1px; max-width:540px; min-width:326px; padding:0;
           width:99.375%; width:-webkit-calc(100% - 2px);
           width:calc(100% - 2px);">
  </blockquote>

  <script async src="//www.instagram.com/embed.js"></script>
</div>


###  Flip Follow Move

<div style="max-width:540px; margin:1em auto;">
  <blockquote class="instagram-media"
    data-instgrm-permalink="https://www.instagram.com/reel/DPhx6iIjSIi/?utm_source=ig_embed&utm_campaign=loading"
    data-instgrm-version="14"
    style="background:#FFF; border:0; border-radius:3px;
           box-shadow:0 0 1px rgba(0,0,0,0.5),
                       0 1px 10px rgba(0,0,0,0.15);
           padding:0; width:100%;">
  </blockquote>
</div>

<script async src="https://www.instagram.com/embed.js"></script>



## Footwork



### Footwork Cross Overs

<div style="text-align:center;">
  <blockquote class="instagram-media"
    data-instgrm-captioned
    data-instgrm-permalink="https://www.instagram.com/p/CGENhNnAG9W/?utm_source=ig_embed&amp;utm_campaign=loading"
    data-instgrm-version="14"
    style="background:#FFF; border:0; border-radius:3px;
           box-shadow:0 0 1px 0 rgba(0,0,0,0.5),
                       0 1px 10px 0 rgba(0,0,0,0.15);
           margin:1px; max-width:540px; min-width:326px; padding:0;
           width:99.375%; width:-webkit-calc(100% - 2px);
           width:calc(100% - 2px);">
  </blockquote>
  <script async src="//www.instagram.com/embed.js"></script>
</div>



### Triangle Drop Shuffle

<div style="text-align:center;">
<iframe width="560" height="315"
        src="https://www.youtube.com/embed/aXXhaomzYZA?start=382&end=395&autoplay=0&mute=1&loop=0&playlist=aXXhaomzYZA"
        frameborder="0"
        allow="autoplay; encrypted-media"
        allowfullscreen>
</iframe>
</div>



### Advanced Triangle Drill

<div style="text-align:center;">
<iframe width="560" height="315"
        src="https://www.youtube.com/embed/nwT3mBgwQQQ?start=78&end=110&autoplay=0&mute=1&loop=0&playlist=nwT3mBgwQQQ"
        frameborder="0"
        allow="autoplay; encrypted-media"
        allowfullscreen>
</iframe>
</div>



### Footwork To Power with Shuffle

<div style="text-align:center;">
<iframe width="560" height="315"
        src="https://www.youtube.com/embed/aXXhaomzYZA?start=447&end=490&autoplay=0&mute=1&loop=0&playlist=aXXhaomzYZA"
        frameborder="0"
        allow="autoplay; encrypted-media"
        allowfullscreen>
</iframe>
</div>




### Chatter and Hunt

<div style="max-width:540px; margin:1px auto;">
  <blockquote class="instagram-media" data-instgrm-permalink="https://www.instagram.com/reel/DHe0jNyyoBv/?utm_source=ig_embed&utm_campaign=loading" data-instgrm-version="14" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; padding:0; width:100%;">
  </blockquote>
  <script async src="//www.instagram.com/embed.js"></script>
</div>


## Other



###  Backhand, Forehand and Fly

<div style="text-align:center;">
  <blockquote 
    class="instagram-media"
    data-instgrm-captioned
    data-instgrm-permalink="https://www.instagram.com/reel/DFGpLTLyOoq/?utm_source=ig_embed&utm_campaign=loading"
    data-instgrm-version="14"
    style="background:#FFF; border:0; border-radius:3px;
           box-shadow:0 0 1px 0 rgba(0,0,0,0.5),
                       0 1px 10px 0 rgba(0,0,0,0.15);
           margin:1px; max-width:540px; min-width:326px; padding:0;
           width:99.375%; width:-webkit-calc(100% - 2px);
           width:calc(100% - 2px);">
  </blockquote>

  <script async src="//www.instagram.com/embed.js"></script>
</div>



### Catching and Tagging

<div style="text-align:center;">
  <blockquote class="instagram-media"
    data-instgrm-captioned
    data-instgrm-permalink="https://www.instagram.com/p/CNlrKVug0aI/?utm_source=ig_embed&amp;utm_campaign=loading"
    data-instgrm-version="14"
    style="background:#FFF; border:0; border-radius:3px;
           box-shadow:0 0 1px 0 rgba(0,0,0,0.5),
                       0 1px 10px 0 rgba(0,0,0,0.15);
           margin:1px; max-width:540px; min-width:326px; padding:0;
           width:99.375%; width:-webkit-calc(100% - 2px);
           width:calc(100% - 2px);">
  </blockquote>
  <script async src="//www.instagram.com/embed.js"></script>
</div>


### Group Tag Drill

<div style="text-align:center;">
  <blockquote class="instagram-media"
    data-instgrm-captioned
    data-instgrm-permalink="https://www.instagram.com/p/CUNz6wrLvgq/?utm_source=ig_embed&amp;utm_campaign=loading"
    data-instgrm-version="14"
    style="background:#FFF; border:0; border-radius:3px;
           box-shadow:0 0 1px 0 rgba(0,0,0,0.5),
                       0 1px 10px 0 rgba(0,0,0,0.15);
           margin:1px; max-width:540px; min-width:326px; padding:0;
           width:99.375%; width:-webkit-calc(100% - 2px);
           width:calc(100% - 2px);">
  </blockquote>
  <script async src="//www.instagram.com/embed.js"></script>
</div>








##  First Base Specific Drills

### Batted Picks

<div style="text-align:center;">
  <blockquote class="instagram-media"
    data-instgrm-captioned
    data-instgrm-permalink="https://www.instagram.com/p/CCJLkibArT8/?utm_source=ig_embed&amp;utm_campaign=loading"
    data-instgrm-version="14"
    style="background:#FFF; border:0; border-radius:3px;
           box-shadow:0 0 1px 0 rgba(0,0,0,0.5),
                       0 1px 10px 0 rgba(0,0,0,0.15);
           margin:1px; max-width:540px; min-width:326px; padding:0;
           width:99.375%; width:-webkit-calc(100% - 2px);
           width:calc(100% - 2px);">
  </blockquote>
  <script async src="//www.instagram.com/embed.js"></script>
</div>


###  First Base Footwork

<div style="text-align:center;">
  <blockquote class="instagram-media"
    data-instgrm-captioned
    data-instgrm-permalink="https://www.instagram.com/p/CTSfb5_hFVd/?utm_source=ig_embed&amp;utm_campaign=loading"
    data-instgrm-version="14"
    style="background:#FFF; border:0; border-radius:3px;
           box-shadow:0 0 1px 0 rgba(0,0,0,0.5),
                       0 1px 10px 0 rgba(0,0,0,0.15);
           margin:1px; max-width:540px; min-width:326px; padding:0;
           width:99.375%; width:-webkit-calc(100% - 2px);
           width:calc(100% - 2px);">
  </blockquote>
  <script async src="//www.instagram.com/embed.js"></script>
</div>


<div style="max-width:540px; margin:1em auto;">
  <blockquote class="instagram-media"
    data-instgrm-permalink="https://www.instagram.com/reel/DRVKI3vkkai/?utm_source=ig_embed&utm_campaign=loading"
    data-instgrm-version="14"
    style="background:#FFF; border:0; border-radius:3px;
           box-shadow:0 0 1px rgba(0,0,0,0.5),
                       0 1px 10px rgba(0,0,0,0.15);
           padding:0; width:100%;">
  </blockquote>
</div>

<script async src="https://www.instagram.com/embed.js"></script>

##  Third Base Specific Drills

### Throwing on the Run (Bunt Defense)

<div style="text-align:center;">
  <blockquote class="instagram-media"
    data-instgrm-captioned
    data-instgrm-permalink="https://www.instagram.com/p/Bv2u0BijnBY/?utm_source=ig_embed&amp;utm_campaign=loading"
    data-instgrm-version="14"
    style="background:#FFF; border:0; border-radius:3px;
           box-shadow:0 0 1px 0 rgba(0,0,0,0.5),
                       0 1px 10px 0 rgba(0,0,0,0.15);
           margin:1px; max-width:540px; min-width:326px; padding:0;
           width:99.375%; width:-webkit-calc(100% - 2px);
           width:calc(100% - 2px);">
  </blockquote>
  <script async src="//www.instagram.com/embed.js"></script>
</div>