# Catching Drills


## Stances - Why Catch Wtih Knee DOwn {-}


<div style="text-align:center;">
<iframe width="560" height="315"
        src="https://www.youtube.com/embed/9KL4TNtCBXI?start=105&end=349&autoplay=0&mute=1&loop=0&playlist=9KL4TNtCBXI"
        frameborder="0"
        allow="autoplay; encrypted-media"
        allowfullscreen>
</iframe>
</div>


Left knee down for RH batter (because umpire is behind left shoulder).

Right knee down for LH batter (because umpire is behind right shoulder).




## Receiving & Framing

### Short Hops

<div style="text-align:center;">
<iframe width="560" height="315"
        src="https://www.youtube.com/embed/HUPsI0avA98?autoplay=1&mute=1&loop=1&playlist=HUPsI0avA98"
        frameborder="0"
        allow="autoplay; encrypted-media"
        allowfullscreen>
</iframe>
</div>


### Plyo Receiving

<div style="text-align:center;">
<iframe width="560" height="315"
        src="https://www.youtube.com/embed/8ZqAyp4sHx0?autoplay=1&mute=1&loop=1&playlist=8ZqAyp4sHx0"
        frameborder="0"
        allow="autoplay; encrypted-media"
        allowfullscreen>
</iframe>
</div>

### Dry Feels

<div style="text-align:center;">
<iframe width="560" height="315"
        src="https://www.youtube.com/embed/-uBaPb6zFSg?autoplay=1&mute=1&loop=1&playlist=-uBaPb6zFSg"
        frameborder="0"
        allow="autoplay; encrypted-media"
        allowfullscreen>
</iframe>
</div>

### Barehand Flips

<div style="text-align:center;">
<iframe width="560" height="315"
        src="https://www.youtube.com/embed/SNu8FwF1Qss?autoplay=1&mute=1&loop=1&playlist=SNu8FwF1Qss"
        frameborder="0"
        allow="autoplay; encrypted-media"
        allowfullscreen>
</iframe>
</div>



###  Super Basic For Beginners

div style="text-align:center;">
  <blockquote class="instagram-media"
    data-instgrm-captioned
    data-instgrm-permalink="https://www.instagram.com/p/CVBqgNtg_LQ/?utm_source=ig_embed&amp;utm_campaign=loading"
    data-instgrm-version="14"
    style="background:#FFF; border:0; border-radius:3px;
           box-shadow:0 0 1px 0 rgba(0,0,0,0.5),
                       0 1px 10px 0 rgba(0,0,0,0.15);
           margin:1px; max-width:540px; min-width:326px; padding:0;
           width:99.375%; width:-webkit-calc(100% - 2px);
           width:calc(100% - 2px);">
  </blockquote>
  <script async src="//www.instagram.com/embed.js"></script>
</div>


##  Blocking Drills
Side-to-side slides, reaction balls

##  Throwing Drills


### Work the Transfers

<iframe width="560" height="315"
  src="https://www.youtube.com/embed/wd8eYHPhAJA?start=25&end=61"
  title="YouTube video"
  frameborder="0"
  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
  allowfullscreen>
</iframe>

### Work Foot Down

<iframe width="560" height="315"
  src="https://www.youtube.com/embed/wd8eYHPhAJA?start=62&end=88"
  title="YouTube video"
  frameborder="0"
  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
  allowfullscreen>
</iframe>

### Footwork Standing Up

<iframe width="560" height="315"
  src="https://www.youtube.com/embed/wd8eYHPhAJA?start=89&end=116"
  title="YouTube video"
  frameborder="0"
  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
  allowfullscreen>
</iframe>

### Shoulder Switch

<iframe width="560" height="315"
  src="https://www.youtube.com/embed/wd8eYHPhAJA?start=115&end=173"
  title="YouTube video"
  frameborder="0"
  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
  allowfullscreen>
</iframe>


### Throw from Knees

<iframe width="560" height="315"
  src="https://www.youtube.com/embed/wd8eYHPhAJA?start=173&end=206"
  title="YouTube video"
  frameborder="0"
  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
  allowfullscreen>
</iframe>

### The Math Behind A Sub 2.0 Pop Time

<div style="text-align:center;">
<iframe width="560" height="315"
        src="https://www.youtube.com/embed/EXm_vkJA6hs?autoplay=0&mute=1&loop=0&playlist=EXm_vkJA6hs"
        frameborder="0"
        allow="autoplay; encrypted-media"
        allowfullscreen>
</iframe>
</div>


### Molina Drills

<div style="max-width:540px; margin:1em auto;">
  <blockquote class="instagram-media"
    data-instgrm-permalink="https://www.instagram.com/p/Bd3Ivijl0F-/?utm_source=ig_embed&utm_campaign=loading"
    data-instgrm-version="14"
    style="background:#FFF; border:0; border-radius:3px;
           box-shadow:0 0 1px rgba(0,0,0,0.5),
                       0 1px 10px rgba(0,0,0,0.15);
           padding:0; width:100%;">
  </blockquote>
</div>

<script async src="https://www.instagram.com/embed.js"></script>


##  Game Management
Signs, pitcher communication

