# Hitting Drills

## Mechanics & Fundamentals

###  Where do we Hit The Ball?

<div style="text-align:center;">
  <blockquote class="instagram-media"
    data-instgrm-captioned
    data-instgrm-permalink="https://www.instagram.com/p/CUSSWNXAaZi/?utm_source=ig_embed&amp;utm_campaign=loading"
    data-instgrm-version="14"
    style="background:#FFF; border:0; border-radius:3px;
           box-shadow:0 0 1px 0 rgba(0,0,0,0.5),
                       0 1px 10px 0 rgba(0,0,0,0.15);
           margin:1px; max-width:540px; min-width:326px; padding:0;
           width:99.375%; width:-webkit-calc(100% - 2px);
           width:calc(100% - 2px);">
  </blockquote>
  <script async src="//www.instagram.com/embed.js"></script>
</div>


### What is a Disconnected Swing

<div style="text-align:center;">
<iframe width="560" height="315"
        src="https://www.youtube.com/embed/01VWfZ09Vh4?start=27&end=100&autoplay=1&mute=1&loop=0&playlist=01VWfZ09Vh4"
        frameborder="0"
        allow="autoplay; encrypted-media"
        allowfullscreen>
</iframe>
</div>

Why is a Disconnected Swing Bad? 

-  You get long,  
-  You get slow,  
-  Pop the ball up,  


### Turn Behind the Baseball

<div style="max-width:540px; margin:1em auto;">
  <blockquote class="instagram-media"
    data-instgrm-permalink="https://www.instagram.com/reel/DMQ96jpSkGA/?utm_source=ig_embed&utm_campaign=loading"
    data-instgrm-version="14"
    style="background:#FFF; border:0; border-radius:3px;
           box-shadow:0 0 1px rgba(0,0,0,0.5),
                       0 1px 10px rgba(0,0,0,0.15);
           padding:0; width:100%;">
  </blockquote>
</div>

<script async src="https://www.instagram.com/embed.js"></script>


###  Hands By Your Shoulder (Don't load too much)

<iframe width="560" height="315"
  src="https://www.youtube.com/embed/cckNn47WGY8"
  title="YouTube video"
  frameborder="0"
  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
  allowfullscreen>
</iframe>


##  Med Ball Work




### Med Ball Swings

<div style="text-align:center;">
  <blockquote class="instagram-media"
    data-instgrm-captioned
    data-instgrm-permalink="https://www.instagram.com/p/CUC6JAZgC9K/?utm_source=ig_embed&amp;utm_campaign=loading"
    data-instgrm-version="14"
    style="background:#FFF; border:0; border-radius:3px;
           box-shadow:0 0 1px 0 rgba(0,0,0,0.5),
                       0 1px 10px 0 rgba(0,0,0,0.15);
           margin:1px; max-width:540px; min-width:326px; padding:0;
           width:99.375%; width:-webkit-calc(100% - 2px);
           width:calc(100% - 2px);">
  </blockquote>
  <script async src="//www.instagram.com/embed.js"></script>
</div>


###  Med Ball Routine



<iframe width="560" height="315"
  src="https://www.youtube.com/embed/r9fs-HGCZTs"
  title="YouTube video"
  frameborder="0"
  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
  allowfullscreen>
</iframe>


#### Shuffle and Throw

<iframe width="560" height="315"
  src="https://www.youtube.com/embed/r9fs-HGCZTs?start=149&end=185"
  title="YouTube video clip"
  frameborder="0"
  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
  allowfullscreen>
</iframe>


#### Step Back and Throw

<iframe width="560" height="315"
  src="https://www.youtube.com/embed/r9fs-HGCZTs?start=185&end=215"
  title="YouTube video clip"
  frameborder="0"
  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
  allowfullscreen>
</iframe>


#### Flamingo (Front Leg)

<iframe width="560" height="315"
  src="https://www.youtube.com/embed/r9fs-HGCZTs?start=215&end=249"
  title="YouTube video clip"
  frameborder="0"
  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
  allowfullscreen>
</iframe>

#### Boxers

<iframe width="560" height="315"
  src="https://www.youtube.com/embed/r9fs-HGCZTs?start=248&end=270"
  title="YouTube video clip"
  frameborder="0"
  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
  allowfullscreen>
</iframe>

#### Back Leg Hop

<iframe width="560" height="315"
  src="https://www.youtube.com/embed/r9fs-HGCZTs?start=270&end=299"
  title="YouTube video clip"
  frameborder="0"
  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
  allowfullscreen>
</iframe>

#### One Knee Down

<iframe width="560" height="315"
  src="https://www.youtube.com/embed/r9fs-HGCZTs?start=327&end=377"
  title="YouTube video clip"
  frameborder="0"
  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
  allowfullscreen>
</iframe>




##  Tee Work Drills

### Palm Up, Palm Down

<div style="text-align:center;">
  <blockquote class="instagram-media"
    data-instgrm-captioned
    data-instgrm-permalink="https://www.instagram.com/p/CP8l1R1gG57/?utm_source=ig_embed&amp;utm_campaign=loading"
    data-instgrm-version="14"
    style="background:#FFF; border:0; border-radius:3px;
           box-shadow:0 0 1px 0 rgba(0,0,0,0.5),
                       0 1px 10px 0 rgba(0,0,0,0.15);
           margin:1px; max-width:540px; min-width:326px; padding:0;
           width:99.375%; width:-webkit-calc(100% - 2px);
           width:calc(100% - 2px);">
  </blockquote>
  <script async src="//www.instagram.com/embed.js"></script>
</div>


### Ball Drill for Disconnected Swing


<div style="text-align:center;">
<iframe width="560" height="315"
        src="https://www.youtube.com/embed/01VWfZ09Vh4?start=100&end=252&autoplay=1&mute=1&loop=0&playlist=01VWfZ09Vh4"
        frameborder="0"
        allow="autoplay; encrypted-media"
        allowfullscreen>
</iframe>
</div>




### Ball on Neck Drill for Disconnected Swing


<div style="text-align:center;">
<iframe width="560" height="315"
        src="https://www.youtube.com/embed/01VWfZ09Vh4?start=253&end=314&autoplay=1&mute=1&loop=0&playlist=01VWfZ09Vh4"
        frameborder="0"
        allow="autoplay; encrypted-media"
        allowfullscreen>
</iframe>
</div>


### Stay Back Ramp Drill

<iframe width="315" height="560"
  src="https://www.youtube.com/embed/OgrHcCTSkBE"
  title="YouTube Short"
  frameborder="0"
  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
  allowfullscreen>
</iframe>

###  Babe Ruth Drill

<iframe width="315" height="560"
  src="https://www.youtube.com/embed/YGey75fmruk"
  title="YouTube Short"
  frameborder="0"
  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
  allowfullscreen>
</iframe>


### Jumpback Swings

<div style="text-align:center;">
  <blockquote class="instagram-media"
    data-instgrm-captioned
    data-instgrm-permalink="https://www.instagram.com/p/CUz6ilTANRx/?utm_source=ig_embed&amp;utm_campaign=loading"
    data-instgrm-version="14"
    style="background:#FFF; border:0; border-radius:3px;
           box-shadow:0 0 1px 0 rgba(0,0,0,0.5),
                       0 1px 10px 0 rgba(0,0,0,0.15);
           margin:1px; max-width:540px; min-width:326px; padding:0;
           width:99.375%; width:-webkit-calc(100% - 2px);
           width:calc(100% - 2px);">
  </blockquote>
  <script async src="//www.instagram.com/embed.js"></script>
</div>


### Happy Gilmore

<iframe width="560" height="315"
  src="https://www.youtube.com/embed/OEkDXHoqtcE?start=0&end=60"
  title="YouTube video clip"
  frameborder="0"
  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
  allowfullscreen>
</iframe>

###  Balancing on your back leg before you swing (Teacherman Drill)

<iframe width="560" height="315"
  src="https://www.youtube.com/embed/OEkDXHoqtcE?start=58&end=114"
  title="YouTube video clip"
  frameborder="0"
  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
  allowfullscreen>
</iframe>

### Jump Back Swings

<iframe width="560" height="315"
  src="https://www.youtube.com/embed/OEkDXHoqtcE?start=114&end=156"
  title="YouTube video clip"
  frameborder="0"
  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
  allowfullscreen>
</iframe>

###  Load Pause Swings

<iframe width="560" height="315"
  src="https://www.youtube.com/embed/OEkDXHoqtcE?start=156&end=213"
  title="YouTube video clip"
  frameborder="0"
  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
  allowfullscreen>
</iframe>

###  Knee Swings

<iframe width="560" height="315"
  src="https://www.youtube.com/embed/OEkDXHoqtcE?start=213&end=254"
  title="YouTube video clip"
  frameborder="0"
  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
  allowfullscreen>
</iframe>

### 90 Degree Swings

<iframe width="315" height="560"
  src="https://www.youtube.com/embed/8Zq5WEU6HlM"
  title="YouTube Shorts video"
  frameborder="0"
  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
  allowfullscreen>
</iframe>


### Big Papi

<iframe width="560" height="315"
  src="https://www.youtube.com/embed/6EokTXNijS8?start=214&end=268"
  title="YouTube video clip"
  frameborder="0"
  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
  allowfullscreen>
</iframe>


##  Front Toss / Live BP

### Basic Font Toss

<div style="text-align:center;">
  <blockquote class="instagram-media"
    data-instgrm-captioned
    data-instgrm-permalink="https://www.instagram.com/p/CNkNT8YgU3F/?utm_source=ig_embed&amp;utm_campaign=loading"
    data-instgrm-version="14"
    style="background:#FFF; border:0; border-radius:3px;
           box-shadow:0 0 1px 0 rgba(0,0,0,0.5),
                       0 1px 10px 0 rgba(0,0,0,0.15);
           margin:1px; max-width:540px; min-width:326px; padding:0;
           width:99.375%; width:-webkit-calc(100% - 2px);
           width:calc(100% - 2px);">
  </blockquote>
  <script async src="//www.instagram.com/embed.js"></script>
</div>

### Front Toss with Shadow Tee

<div style="text-align:center;">
  <blockquote class="instagram-media"
    data-instgrm-captioned
    data-instgrm-permalink="https://www.instagram.com/p/CUvRWCZs0Td/?utm_source=ig_embed&amp;utm_campaign=loading"
    data-instgrm-version="14"
    style="background:#FFF; border:0; border-radius:3px;
           box-shadow:0 0 1px 0 rgba(0,0,0,0.5),
                       0 1px 10px 0 rgba(0,0,0,0.15);
           margin:1px; max-width:540px; min-width:326px; padding:0;
           width:99.375%; width:-webkit-calc(100% - 2px);
           width:calc(100% - 2px);">
  </blockquote>
  <script async src="//www.instagram.com/embed.js"></script>
</div>




##  Power & Bat Speed Drills
Resistance bands, overload/underload bats

## Situational Hitting

### Slapping

<div style="text-align:center;">
  <blockquote class="instagram-media"
    data-instgrm-captioned
    data-instgrm-permalink="https://www.instagram.com/p/CPtlvM0AgPr/?utm_source=ig_embed&amp;utm_campaign=loading"
    data-instgrm-version="14"
    style="background:#FFF; border:0; border-radius:3px;
           box-shadow:0 0 1px 0 rgba(0,0,0,0.5),
                       0 1px 10px 0 rgba(0,0,0,0.15);
           margin:1px; max-width:540px; min-width:326px; padding:0;
           width:99.375%; width:-webkit-calc(100% - 2px);
           width:calc(100% - 2px);">
  </blockquote>
  <script async src="//www.instagram.com/embed.js"></script>
</div>
