# Dailies by Position

## Catcher Dailies

### Receiving Progression:

*  Weighted ball rolls (10 - 15) no glove
*  Weighted ball short hops (10 -15) no glove
*  Weighted ball high pitches (10 - 15) no glove
*  Fastballs with glove
*  Change pitches

<div style="max-width:540px; margin:1em auto;">
  <blockquote class="instagram-media"
    data-instgrm-permalink="https://www.instagram.com/reel/DR0JtwhCZWb/?utm_source=ig_embed&utm_campaign=loading"
    data-instgrm-version="14"
    style="background:#FFF; border:0; border-radius:3px;
           box-shadow:0 0 1px rgba(0,0,0,0.5),
                       0 1px 10px rgba(0,0,0,0.15);
           padding:0; width:100%;">
  </blockquote>
</div>

<script async src="https://www.instagram.com/embed.js"></script>


### Throwing Footwork Routine:

*  Transfer the ball
*  Right foot down as you catch
*  Footwork standing up
*  Shoulder switch
*  Throw from knees

<div style="position:relative;padding-bottom:56.25%;height:0;overflow:hidden;">
  <iframe
    src="https://www.youtube.com/embed/wd8eYHPhAJA"
    style="position:absolute;top:0;left:0;width:100%;height:100%;"
    frameborder="0"
    allowfullscreen>
  </iframe>
</div>


###  Blocking Routine:

*  Block side-to-side
*  Preset blocking
*  Block-reverse
*  Circle blocks

<div style="max-width:540px; margin:1em auto;">
  <blockquote class="instagram-media"
    data-instgrm-permalink="https://www.instagram.com/reel/DE_PJ3QOQOd/?utm_source=ig_embed&utm_campaign=loading"
    data-instgrm-version="14"
    style="background:#FFF; border:0; border-radius:3px;
           box-shadow:0 0 1px rgba(0,0,0,0.5),
                       0 1px 10px rgba(0,0,0,0.15);
           padding:0; width:100%;">
  </blockquote>
</div>

<script async src="https://www.instagram.com/embed.js"></script>


## Infield Dailies



### Knee Short Hop Daily

<div style="text-align:center;">
<iframe width="560" height="315"
        src="https://www.youtube.com/embed/aXXhaomzYZA?start=183&end=196&autoplay=0&mute=1&loop=0&playlist=aXXhaomzYZA"
        frameborder="0"
        allow="autoplay; encrypted-media"
        allowfullscreen>
</iframe>
</div>

<div style="max-width:540px; margin:1px auto;">
  <blockquote
    class="instagram-media"
    data-instgrm-permalink="https://www.instagram.com/p/BwPZ_RdgrHJ/?utm_source=ig_embed&utm_campaign=loading"
    data-instgrm-version="14"
    style="background:#FFF; border:0; border-radius:3px;
           box-shadow:0 0 1px 0 rgba(0,0,0,0.5),
                       0 1px 10px 0 rgba(0,0,0,0.15);
           padding:0; width:100%;">
  </blockquote>

  <script async src="//www.instagram.com/embed.js"></script>
</div>





### Standing GB, SH, BH

<blockquote class="instagram-media"
  data-instgrm-permalink="https://www.instagram.com/p/BxhYnNVg-i9/"
  data-instgrm-version="14">
</blockquote>

<script async src="https://www.instagram.com/embed.js"></script>

### Ladder Forehands

<iframe width="560" height="315"
  src="https://www.youtube.com/embed/rinG_WltJnY?start=0&end=45"
  title="YouTube video clip"
  frameborder="0"
  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
  allowfullscreen>
</iframe>


### Ladder Forehand/ Backhand

<iframe width="560" height="315"
  src="https://www.youtube.com/embed/rinG_WltJnY?start=45"
  title="YouTube video clip"
  frameborder="0"
  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
  allowfullscreen>
</iframe>


### Drop Ball Drill

<div style="position:relative;padding-bottom:56.25%;height:0;overflow:hidden;">
  <iframe
    src="https://www.youtube.com/embed/5YUw_Wk46zg?start=55&end=69"
    style="position:absolute;top:0;left:0;width:100%;height:100%;"
    frameborder="0"
    allowfullscreen>
  </iframe>
</div>



### Ladder Drop Step Daily

<div style="text-align:center;">
<iframe width="560" height="315"
        src="https://www.youtube.com/embed/aXXhaomzYZA?start=197&end=205&autoplay=0&mute=1&loop=0&playlist=aXXhaomzYZA"
        frameborder="0"
        allow="autoplay; encrypted-media"
        allowfullscreen>
</iframe>
</div>


### No Panic

<iframe width="560" height="315"
  src="https://www.youtube.com/embed/5YUw_Wk46zg?start=165&end=177"
  title="YouTube video clip"
  frameborder="0"
  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
  allowfullscreen>
</iframe>


### Over and Backs

<div style="text-align:center;">
  <blockquote class="instagram-media"
    data-instgrm-captioned
    data-instgrm-permalink="https://www.instagram.com/reel/DEVJpXqPSUa/?utm_source=ig_embed&amp;utm_campaign=loading"
    data-instgrm-version="14"
    style="background:#FFF; border:0; border-radius:3px;
           box-shadow:0 0 1px 0 rgba(0,0,0,0.5),
                       0 1px 10px 0 rgba(0,0,0,0.15);
           margin:1px; max-width:540px; min-width:326px; padding:0;
           width:99.375%; width:-webkit-calc(100% - 2px);
           width:calc(100% - 2px);">
  </blockquote>
  <script async src="//www.instagram.com/embed.js"></script>
</div>


##  Outfield Dailies



###  Drop Step Barehand (45 – 60 degrees)	

Throw a ball with this drill (no glove)

<iframe width="560" height="315"
  src="https://www.youtube.com/embed/R4VMjrTo3AA?start=73&end=193"
  title="YouTube video clip"
  frameborder="0"
  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
  allowfullscreen>
</iframe>


###  Drop Step Barehand (70 – 90 degrees)

Throw a ball with this drill (no glove)

<iframe width="560" height="315"
  src="https://www.youtube.com/embed/R4VMjrTo3AA?start=193&end=225"
  title="YouTube video clip"
  frameborder="0"
  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
  allowfullscreen>
</iframe>


###  Change Direction Drill

Throw a ball with this drill (no glove)

<iframe width="560" height="315"
  src="https://www.youtube.com/embed/R4VMjrTo3AA?start=225&end=294"
  title="YouTube video clip"
  frameborder="0"
  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
  allowfullscreen>
</iframe>


###  Get Behind the Ball



###  Ground Ball Preload

Throw into a net

<iframe width="560" height="315"
  src="https://www.youtube.com/embed/R4VMjrTo3AA?start=285&end=404"
  title="YouTube video clip"
  frameborder="0"
  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
  allowfullscreen>
</iframe>

###  Rolled Ground Balls

Same as preload, but add footwork

<iframe width="560" height="315"
  src="https://www.youtube.com/embed/R4VMjrTo3AA?start=405&end=430"
  title="YouTube video clip"
  frameborder="0"
  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
  allowfullscreen>
</iframe>


###  Off the Wall Drill


<iframe width="560" height="315"
  src="https://www.youtube.com/embed/R4VMjrTo3AA?start=529&end=642"
  title="YouTube video clip"
  frameborder="0"
  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
  allowfullscreen>
</iframe>



##  First Base Dailies

*  Catch a ball off the wall 10x in front of your face
*  Stride out and catch a ball in front of your face 10x
*  Pick a ball off a wall 10x
*  Pick a ball off a wall on your knee 10x
*  Pick a ball from your partner on your knee 10x
*  Start on the bag and pick a ball from your partner 10x




<div style="max-width:540px; margin:1em auto;">
  <blockquote class="instagram-media"
    data-instgrm-permalink="https://www.instagram.com/reel/DCVDSzNSnOj/?utm_source=ig_embed&utm_campaign=loading"
    data-instgrm-version="14"
    style="background:#FFF; border:0; border-radius:3px;
           box-shadow:0 0 1px rgba(0,0,0,0.5),
                       0 1px 10px rgba(0,0,0,0.15);
           padding:0; width:100%;">
  </blockquote>
</div>

<script async src="https://www.instagram.com/embed.js"></script>