# Conditioning





## Agility Drills

###  5 Cone Deceleration Drill

<div style="max-width:540px; margin:1px auto;">
  <blockquote class="instagram-media" 
      data-instgrm-permalink="https://www.instagram.com/reel/C58uGNPunG_/?utm_source=ig_embed&utm_campaign=loading" 
      data-instgrm-version="14" 
      style="background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; padding:0; width:100%;">
  </blockquote>
  <script async src="//www.instagram.com/embed.js"></script>
</div>

### Backpedaling COD Drill

<div style="max-width:540px; margin:1px auto;">
  <blockquote class="instagram-media" 
      data-instgrm-permalink="https://www.instagram.com/reel/DQwxA1RjXnq/?utm_source=ig_embed&utm_campaign=loading" 
      data-instgrm-version="14" 
      style="background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; padding:0; width:100%;">
  </blockquote>
  <script async src="//www.instagram.com/embed.js"></script>
</div>


###  Lateral Power and COD Drill

<div style="max-width:540px; margin:1px auto;">
  <blockquote class="instagram-media" 
      data-instgrm-permalink="https://www.instagram.com/reel/DP6d2kHDloZ/?utm_source=ig_embed&utm_campaign=loading" 
      data-instgrm-version="14" 
      style="background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; padding:0; width:100%;">
  </blockquote>
  <script async src="//www.instagram.com/embed.js"></script>
</div>

###  Turn and Run Drill Progression

<div style="max-width:540px; margin:1px auto;">
  <blockquote class="instagram-media" 
      data-instgrm-permalink="https://www.instagram.com/reel/DM2v1NssR7-/?utm_source=ig_embed&utm_campaign=loading" 
      data-instgrm-version="14" 
      style="background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; padding:0; width:100%;">
  </blockquote>
  <script async src="//www.instagram.com/embed.js"></script>
</div>

###  Lateral Bound to 90 Degree Broad Jump

<div style="max-width:540px; margin:1em auto;">
  <blockquote class="instagram-media" 
      data-instgrm-permalink="https://www.instagram.com/reel/DLuoU0RsjpC/?utm_source=ig_embed&utm_campaign=loading" 
      data-instgrm-version="14" 
      style="background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px rgba(0,0,0,0.5),0 1px 10px rgba(0,0,0,0.15); padding:0; width:100%;">
  </blockquote>
  <script async src="https://www.instagram.com/embed.js"></script>
</div>

###  Cop Around Cones Drill


<div style="max-width:540px; margin:1em auto;">
  <blockquote class="instagram-media" 
      data-instgrm-permalink="https://www.instagram.com/reel/DJUXLI3ObSu/?utm_source=ig_embed&utm_campaign=loading" 
      data-instgrm-version="14" 
      style="background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px rgba(0,0,0,0.5),0 1px 10px rgba(0,0,0,0.15); padding:0; width:100%;">
  </blockquote>
  <script async src="https://www.instagram.com/embed.js"></script>
</div>

###  PunchWall Drill

<div style="max-width:540px; margin:1em auto;">
  <blockquote class="instagram-media" 
      data-instgrm-permalink="https://www.instagram.com/reel/DGQxCCLO8Cd/?utm_source=ig_embed&utm_campaign=loading" 
      data-instgrm-version="14" 
      style="background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px rgba(0,0,0,0.5),0 1px 10px rgba(0,0,0,0.15); padding:0; width:100%;">
  </blockquote>
  <script async src="https://www.instagram.com/embed.js"></script>
</div>



###  Circuit Ladder, Gates, Rails

<div style="text-align:center;">
  <blockquote class="instagram-media"
    data-instgrm-captioned
    data-instgrm-permalink="https://www.instagram.com/p/CUdKx9Fgx52/?utm_source=ig_embed&amp;utm_campaign=loading"
    data-instgrm-version="14"
    style="background:#FFF; border:0; border-radius:3px;
           box-shadow:0 0 1px 0 rgba(0,0,0,0.5),
                       0 1px 10px 0 rgba(0,0,0,0.15);
           margin:1px; max-width:540px; min-width:326px; padding:0;
           width:99.375%; width:-webkit-calc(100% - 2px);
           width:calc(100% - 2px);">
  </blockquote>
  <script async src="//www.instagram.com/embed.js"></script>
</div>

### Ladder Quick Feet Come Around

<div style="text-align:center;">
  <blockquote class="instagram-media"
    data-instgrm-captioned
    data-instgrm-permalink="https://www.instagram.com/p/CBiprlOgChk/?utm_source=ig_embed&amp;utm_campaign=loading"
    data-instgrm-version="14"
    style="background:#FFF; border:0; border-radius:3px;
           box-shadow:0 0 1px 0 rgba(0,0,0,0.5),
                       0 1px 10px 0 rgba(0,0,0,0.15);
           margin:1px; max-width:540px; min-width:326px; padding:0;
           width:99.375%; width:-webkit-calc(100% - 2px);
           width:calc(100% - 2px);">
  </blockquote>
  <script async src="//www.instagram.com/embed.js"></script>
</div>

### Quick Feet

<div style="text-align:center;">
  <blockquote 
    class="instagram-media"
    data-instgrm-captioned
    data-instgrm-permalink="https://www.instagram.com/reel/DJJ6AO7xCO8/?utm_source=ig_embed&amp;utm_campaign=loading"
    data-instgrm-version="14"
    style="background:#FFF; border:0; border-radius:3px;
           box-shadow:0 0 1px 0 rgba(0,0,0,0.5),
                       0 1px 10px 0 rgba(0,0,0,0.15);
           margin:1px; max-width:540px; min-width:326px; padding:0;
           width:99.375%; width:-webkit-calc(100% - 2px);
           width:calc(100% - 2px);">
  </blockquote>

  <script async src="//www.instagram.com/embed.js"></script>
</div>


### Sprint Drill

<div style="max-width:540px; margin:1px auto;">
  <blockquote class="instagram-media" data-instgrm-permalink="https://www.instagram.com/reel/C5YgiRGsnNL/?utm_source=ig_embed&utm_campaign=loading" data-instgrm-version="14" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; padding:0; width:100%;">
  </blockquote>
  <script async src="//www.instagram.com/embed.js"></script>
</div>

### Change of Direction and Agility Drill

<div style="max-width:540px; margin:1px auto;">
  <blockquote class="instagram-media" data-instgrm-permalink="https://www.instagram.com/reel/DJ_9QKmuAmT/?utm_source=ig_embed&utm_campaign=loading" data-instgrm-version="14" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; padding:0; width:100%;">
  </blockquote>
  <script async src="//www.instagram.com/embed.js"></script>
</div>



###  Ladder Drills

*  High knees forward
*  High knees laterally
*  Side to side
*  Scissors
*  Open and close
*  Single leg hops
*  In and out

<div style="max-width:540px; margin:1em auto;">
  <blockquote class="instagram-media"
    data-instgrm-permalink="https://www.instagram.com/reel/DGl-2TGvH7L/?utm_source=ig_embed&utm_campaign=loading"
    data-instgrm-version="14"
    style="background:#FFF; border:0; border-radius:3px;
           box-shadow:0 0 1px rgba(0,0,0,0.5),
                       0 1px 10px rgba(0,0,0,0.15);
           padding:0; width:100%;">
  </blockquote>
</div>

<script async src="https://www.instagram.com/embed.js"></script>




##  Footwork

###  Cone Drill (Infielder Footwork)

<div style="text-align:center;">
  <blockquote class="instagram-media"
    data-instgrm-captioned
    data-instgrm-permalink="https://www.instagram.com/p/CMOHMLUglFF/?utm_source=ig_embed&amp;utm_campaign=loading"
    data-instgrm-version="14"
    style="background:#FFF; border:0; border-radius:3px;
           box-shadow:0 0 1px 0 rgba(0,0,0,0.5),
                       0 1px 10px 0 rgba(0,0,0,0.15);
           margin:1px; max-width:540px; min-width:326px; padding:0;
           width:99.375%; width:-webkit-calc(100% - 2px);
           width:calc(100% - 2px);">
  </blockquote>
  <script async src="//www.instagram.com/embed.js"></script>
</div>

###  Staying Low and Giving Ground

<div style="text-align:center;">
  <blockquote class="instagram-media"
    data-instgrm-captioned
    data-instgrm-permalink="https://www.instagram.com/p/CHZFTTJAdDm/?utm_source=ig_embed&amp;utm_campaign=loading"
    data-instgrm-version="14"
    style="background:#FFF; border:0; border-radius:3px;
           box-shadow:0 0 1px 0 rgba(0,0,0,0.5),
                       0 1px 10px 0 rgba(0,0,0,0.15);
           margin:1px; max-width:540px; min-width:326px; padding:0;
           width:99.375%; width:-webkit-calc(100% - 2px);
           width:calc(100% - 2px);">
  </blockquote>
  <script async src="//www.instagram.com/embed.js"></script>
</div>


## Shuffles, Sprint and Change of Direction

<div style="max-width:540px; margin:1em auto;">
  <blockquote class="instagram-media"
    data-instgrm-permalink="https://www.instagram.com/reel/DGOKqfhR38N/?utm_source=ig_embed&utm_campaign=loading"
    data-instgrm-version="14"
    style="background:#FFF; border:0; border-radius:3px;
           box-shadow:0 0 1px rgba(0,0,0,0.5),
                       0 1px 10px rgba(0,0,0,0.15);
           padding:0; width:100%;">
  </blockquote>
</div>

<script async src="https://www.instagram.com/embed.js"></script>

## Strength and Weight Training

### Kettle Bell Work for Softball

<div style="position: relative; width: 315px; height: 560px; max-width:100%; margin:auto;">
  <iframe
    src="https://www.youtube.com/embed/cvLrZxASwhY"
    title="YouTube Short"
    frameborder="0"
    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
    allowfullscreen
    style="position:absolute; width:100%; height:100%; left:0; top:0;">
  </iframe>
</div>


##  Speed Training

### Circle Tag

<div style="max-width:540px; margin:1em auto;">
  <blockquote class="instagram-media"
    data-instgrm-permalink="https://www.instagram.com/reel/C9nsRl0R0eU/?utm_source=ig_embed&utm_campaign=loading"
    data-instgrm-version="14"
    style="background:#FFF; border:0; border-radius:3px;
           box-shadow:0 0 1px rgba(0,0,0,0.5),
                       0 1px 10px rgba(0,0,0,0.15);
           padding:0; width:100%;">
  </blockquote>
</div>

<script async src="https://www.instagram.com/embed.js"></script>